### ISSUE TITLE
Truncating reviews to 250 words

### ISSUE THREAD

**Issue by michaelkhan3** [adeshpande3/LSTM-Sentiment-Analysis#16]
First of all Thanks for the oriole tutorial, I really enjoyed it.

I noticed that you truncate all the reviews to 250 words, I assume this is for convenience.  Would it be better to use all of the use the entire text of the reviews? Do you know of any resources you could point me to that would show me ways of implementing that?

I appreciate your help.

Thanks,
Michael

**Comment by adeshpande3** [comment]
I think it would definitely be ideal to use the entire text, especially because the sentiment or meaning of a text can change with the last sentence(s) of a text. The reasoning I had for truncating was that if I didn't, I would have a lot of padding tokens in my input, and I was a little bit unsure as to how that would affect accuracy/training of the model. I'd be curious to see if you increased the maxLength to 350 or 450 and see if that changes anything in terms of the convergence for training or just the effectiveness in general. Would also recommend just Googling "large length input to rnn".  You'll see quite a few approaches.
