### ISSUE TITLE
Helper function explanation

### ISSUE THREAD

**Issue by dotjrt** [adeshpande3/LSTM-Sentiment-Analysis#19]
I can't seem to understand one line of code from the helper functions: 

`arr[i] = ids[num-1:num]`

Why not just: 

`arr[i] = ids[num-1]`

or: 

`arr[i] = ids[num]`

Thank you.

**Comment by adeshpande3** [comment]
Yeah, sorry for that messy code. I realize I could've made those whole functions more clear and concise.

I wanted arr[i] = ids[num-1:num] instead of arr[i] = ids[num-1] because of the matrix shapes. ids[num-1:num] gives you a matrix of (1, maxSeqLength) while ids[num-1] gives you (maxSeqLength,). In the end, that arr matrix will be of size (batchSize, maxSeqLength) which is what we want.
